baseURL = "https://kymgripal.com"
title = "Kym Michael Gripal"
languageCode = "en-us"
theme = "hello-friend-ng"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
paginate = 10
archetypeDir = "archetypes"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
buildFuture = false
buildExpired = false
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true
enableMissingTranslationPlaceholders = false
disableRSS = true
disableSitemap = false
disable404 = false
disableHugoGeneratorInject = false

[permalinks]
posts = "/posts/:year/:month/:title/"

[author]
name = "Kym Michael Gripal"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
# Metadata mostly used in document's head
#
description = "Portfolio website for Kym Michael Gripal"
keywords = "portfolio, blog, resume, cv, Kym Michael Gripal, kmg0695"
images = [""]
disableReadOtherPosts = false
enableThemeToggle = true
enableSharingButtons = false
justifyContent = true

[params.footer]
trademark = false
rss = false
copyright = false
author = false
topText = []

[params.favicon.color]
mask = "#1b1c1d"
msapplication = "#1b1c1d"
theme = "#1b1c1d"

[params.logo]
logoMark = ">"
logoText = "$ cd ~/"
logoHomeLink = "/"
logoCursorColor = "#56F4FF"
logoCursorPathname = true

[[params.social]]
name = "email"
url = "mailto:hi@kymgripal.com"

[[params.social]]
name = "github"
url = "https://github.com/kmg0695"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/kym-michael-gripal/"

[menu]

[[menu.main]]
identifier = "education"
name = "Education"
url = "education/"

[[menu.main]]
identifier = "skills"
name = "Skills"
url = "skills/"

[[menu.main]]
identifier = "about-me"
name = "About Me"
url = "about-me/"

[[menu.main]]
identifier = "work"
name = "Work Exp."
url = "work/"

[[menu.main]]
identifier = "Projects"
name = "Projects"
url = "projects/"
