baseURL = 'https://kymgripal.com'
languageCode = 'en-us'
title = 'Kym Michael Gripal'
theme = 'typo'
pluralizeListTitles = false
showDate = false

[taxonomies]
tag = 'tags'

[params]
description = "A tech-oriented personal site by Kym Gripal."

# Appearance settings
theme = 'auto'
colorPalette = 'catpuccin'
hideHeader = false

# Intro on main page, content in markdown
# homeIntroTitle = 'Hi there!'
homeIntroContent = "I'm currently rewriting this website. In the meantime, below are the links where you can reach out to me!"

singleDateFormat = '2 Jan 2006'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '02 Jan 2006'

# Breadcrumbs
breadcrumbs = false

showFooter = true
footerContent = "[Hi!](https://www.youtube.com/watch?v=HK578NtfM84)"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/kmg0695/"

[[params.social]]
name = "github"
url = "https://github.com/kmg0695"

[[params.social]]
name = "email"
url = "mailto:hi@kymgripal.com"

# Main menu pages
# [[params.menu]]
# name = "home"
# url = "/"
#
# [[params.menu]]
# name = "projects"
# url = "/projects"
#
# [[params.menu]]
# name = "about-me"
# url = "/about-me"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'catppuccin-frappe'

# Deploy settings
[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|gif|webp)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false
